import os

# --- Paths ---
DATA_DIR   = "/scratch/data/m22aie218/Speech-Understanding/assignment2/data"
OUTPUT_DIR = "/scratch/data/m22aie218/Speech-Understanding/assignment2/output"

REF_VOICE_PATH   = os.path.join(DATA_DIR, "student_voice_ref.wav")    # 60s student recording
SOURCE_AUDIO_PATH = os.path.join(DATA_DIR, "original_segment.wav")    # 10-min lecture clip
OUTPUT_LRL_PATH  = os.path.join(OUTPUT_DIR, "output_LRL_cloned.wav")  # Final synthesised output
DENOISED_PATH    = os.path.join(OUTPUT_DIR, "denoised_segment.wav")   # After Task 1.3

os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# --- ASR Model ---
# Using whisper-medium to balance accuracy and Colab RAM constraints.
# Upgrade to whisper-large-v3 on A100 runtime for best WER.
ASR_MODEL_NAME = "openai/whisper-medium"

# --- Target Low-Resource Language ---
# Bengali (bn) is chosen as the target LRL.
# NOTE: YourTTS supports Bengali via its multilingual VITS backend.
# If Bengali is unavailable in your TTS build, switch to "hi" as a
# fallback and note this limitation in your 1-page implementation note.
TARGET_LRL = "bn"

# --- Frame-level LID ---
FRAME_SHIFT_MS = 10       # 10 ms frames for LID
MIN_F1_LID     = 0.85     # Minimum required F1

# --- Evaluation Thresholds (Assignment §5) ---
MAX_WER_ENG      = 0.15   # WER < 15% for English segments
MAX_WER_HIN      = 0.25   # WER < 25% for Hindi segments
MAX_MCD          = 8.0    # Mel-Cepstral Distortion < 8.0
EER_THRESHOLD    = 0.10   # Equal Error Rate < 10%
LID_SWITCH_MS    = 200    # Timestamp precision for lang switches ≤ 200 ms
SNR_THRESHOLD_DB = 40.0   # Adversarial noise must keep SNR > 40 dB

# --- FGSM Search ---
FGSM_EPSILON_STEP = 0.001
MAX_FGSM_STEPS    = 50

# --- N-gram LM (Task 1.2) ---
# Path to the Speech Course Syllabus text file used to train the N-gram LM.
# Create this file manually by copying the course syllabus into plain text.
SYLLABUS_TEXT_PATH = os.path.join(DATA_DIR, "syllabus.txt")
NGRAM_ORDER = 3  # Trigram LM

# --- Technical Glossary: English term -> Bengali translation (Task 2.2) ---
# Expand this to ≥ 500 entries for full credit.
TECHNICAL_GLOSSARY = {
    "stochastic":           "স্টোকাস্টিক",
    "cepstrum":             "সেপস্ট্রাম",
    "fourier transform":    "ফুরিয়ার রূপান্তর",
    "spectrogram":          "স্পেকট্রোগ্রাম",
    "neural network":       "নিউরাল নেটওয়ার্ক",
    "hidden markov model":  "হিডেন মার্কভ মডেল",
    "dynamic time warping": "ডাইনামিক টাইম ওয়ার্পিং",
    "mel frequency":        "মেল ফ্রিকোয়েন্সি",
    "language model":       "ভাষা মডেল",
    "acoustic model":       "অ্যাকোস্টিক মডেল",
    "beam search":          "বিম সার্চ",
    "word error rate":      "ওয়ার্ড এরর রেট",
    "phoneme":              "ফোনিম",
    "prosody":              "প্রোসোডি",
    "fundamental frequency":"মূল কম্পাঙ্ক",
    "sampling rate":         "স্যাম্পলিং রেট",
    "quantization":          "কোয়ান্টাইজেশন",
    "nyquist frequency":     "নাইকুইস্ট কম্পাঙ্ক",
    "aliasing":              "অ্যালিয়াসিং",
    "windowing":             "উইন্ডোয়িং",
    "hamming window":        "হ্যামিং উইন্ডো",
    "overlap-add":           "ওভারল্যাপ-অ্যাড",
    "short-time fourier transform": "শর্ট-টাইম ফুরিয়ার রূপান্তর",
    "magnitude spectrum":    "ম্যাগনিটিউড স্পেকট্রাম",
    "phase":                 "ফেজ",
    "power spectral density":"পাওয়ার স্পেকট্রাল ডেনসিটি",
    "decibel":               "ডেসিবেল",
    "signal-to-noise ratio": "সিগন্যাল-টু-নয়েজ রেশিও",
    "pre-emphasis":          "প্রি-এমফ্যাসিস",
    "spectral tilt":         "স্পেকট্রাল টিল্ট",
    "cepstral lifting":      "সেপস্ট্রাল লিফটিং",
    "zero crossing rate":    "জিরো ক্রসিং রেট",
    "energy":                "শক্তি",
    "autocorrelation":       "অটো-কো-রিলেশন",
    "linear predictive coding": "লিনিয়ার প্রিডিক্টিভ কোডিং",

    # --- Speech Production & Linguistics ---
    "vocal tract":           "ভোকাল ট্র্যাক্ট",
    "glottis":               "গ্লটিস",
    "vocal folds":           "ভোকাল ফোল্ডস",
    "articulation":          "আর্টিকুলেশন",
    "formant":               "ফরম্যান্ট",
    "pitch":                 "পিচ",
    "intonation":            "ইনটোনেশন",
    "monophthong":           "মনোপথং",
    "diphthong":             "ডিপথং",
    "fricative":             "ফ্রিকেটিভ",
    "plosive":               "প্লোসিভ",
    "nasal":                 "নেজাল",
    "voiced":                "ভয়েসড (ঘোষ)",
    "unvoiced":              "আনভয়েসড (অঘোষ)",
    "aspiration":            "অ্যাসপিরেশন (মহাপ্রাণতা)",
    "syllable":              "সিলেবল (অক্ষর)",
    "morpheme":              "মরফিম (শব্দমূল)",
    "lexicon":               "অভিধান / লেক্সিকন",
    "grapheme":              "গ্রাফিম (লিপি)",
    "allophone":             "অ্যালোফোন",

    # --- Feature Extraction (MFCC & more) ---
    "filter bank":           "ফিল্টার ব্যাংক",
    "mel scale":             "মেল স্কেল",
    "discrete cosine transform": "ডিসক্রিট কোসাইন ট্রান্সফর্ম",
    "delta features":        "ডেল্টা ফিচার",
    "double delta":          "ডাবল ডেল্টা",
    "normalization":         "নরমালাইজেশন",
    "mean variance normalization": "মিন ভ্যারিয়েন্স নরমালাইজেশন",

    # --- Models & Architecture (HMM, DNN, etc.) ---
    "transition probability": "ট্রানজিশন প্রোবাবিলিটি",
    "emission probability":   "এমিশন প্রোবাবিলিটি",
    "viterbi algorithm":     "ভিটারবি অ্যালগরিদম",
    "forward-backward algorithm": "ফরোয়ার্ড-ব্যাকওয়ার্ড অ্যালগরিদম",
    "expectation maximization": "এক্সপেক্টেশন ম্যাক্সিমাইজেশন",
    "hybrid model":          "হাইব্রিড মডেল",
    "end-to-end":            "এন্ড-টু-এন্ড",
    "transformer":           "ট্রান্সফর্মার",
    "attention mechanism":   "অ্যাটেনশন মেকানিজম",
    "self-attention":        "সেলফ-অ্যাটেনশন",
    "encoder":               "এনকোডার",
    "decoder":               "ডিকোডার",
    "connectionist temporal classification": "কানেকশনিস্ট টেম্পোরাল ক্লাসিফিকেশন (CTC)",
    "recurrent neural network": "রিকারেন্ট নিউরাল নেটওয়ার্ক",
    "long short-term memory": "লং শর্ট-টার্ম মেমোরি (LSTM)",

    # --- Synthesis & TTS ---
    "text-to-speech":        "টেক্সট-টু-স্পিচ",
    "vocoder":               "ভোকোডার",
    "prosodic modeling":     "প্রোসোডিক মডেলিং",
    "waveform synthesis":    "ওয়েভফর্ম সিন্থেসিস",
    "concatenative synthesis": "কনক্যাটেনেটিভ সিন্থেসিস",

    # --- Privacy, Unlearning & Security ---
    "machine unlearning":    "মেশিন আনলার্নিং",
    "biometric verification":"বায়োমেট্রিক ভেরিফিকেশন",
    "spoofing attack":       "স্পুফিং অ্যাটাক",
    "anti-spoofing":         "অ্যান্টি-স্পুফিং",
    "voice cloning":         "ভয়েস ক্লোনিং",
    "speaker diarization":   "স্পিকার ডায়ারাইজেশন",
    "membership inference":  "মেম্বারশিপ ইনফারেন্স",

    # --- Infrastructure & Computation ---
    "shared library":        "শেয়ারড লাইব্রেরি",
    "symbolic link":         "সিম্বলিক লিঙ্ক",
    "binary interface":      "বাইনারি ইন্টারফেস",
    "parallel processing":   "প্যারালাল প্রসেসিং",
    "high performance computing": "হাই পারফরম্যান্স কম্পিউটিং",
    "latency":               "ল্যাটেন্সি",
    "throughput":            "থ্রুপুট",
    # --- Additional Signal Processing ---
    "bandwidth":            "ব্যান্ডউইথ",
    "frame size":           "ফ্রেম সাইজ",
    "frame shift":          "ফ্রেম শিফট",
    "frame length":         "ফ্রেম দৈর্ঘ্য",
    "overlap":              "ওভারল্যাপ",
    "window function":      "উইন্ডো ফাংশন",
    "hann window":          "হ্যান উইন্ডো",
    "blackman window":      "ব্ল্যাকম্যান উইন্ডো",
    "rectangular window":   "রেকট্যাঙ্গুলার উইন্ডো",
    "spectral leakage":     "স্পেকট্রাল লিকেজ",
    "frequency resolution": "কম্পাঙ্ক রেজোলিউশন",
    "time resolution":      "সময় রেজোলিউশন",
    "filter":               "ফিল্টার",
    "low-pass filter":      "লো-পাস ফিল্টার",
    "high-pass filter":     "হাই-পাস ফিল্টার",
    "band-pass filter":     "ব্যান্ড-পাস ফিল্টার",
    "band-stop filter":     "ব্যান্ড-স্টপ ফিল্টার",
    "finite impulse response": "ফাইনাইট ইমপালস রেসপন্স (FIR)",
    "infinite impulse response": "ইনফিনাইট ইমপালস রেসপন্স (IIR)",
    "convolution":          "কনভলিউশন",
    "correlation":          "করিলেশন",
    "discrete fourier transform": "ডিসক্রিট ফুরিয়ার ট্রান্সফর্ম",
    "fast fourier transform": "ফাস্ট ফুরিয়ার ট্রান্সফর্ম (FFT)",
    "inverse fourier transform": "ইনভার্স ফুরিয়ার ট্রান্সফর্ম",
    "phase unwrapping":     "ফেজ আনর্যাপিং",
    "spectral envelope":    "স্পেকট্রাল এনভেলপ",
    "harmonic":             "হারমনিক",
    "subharmonic":          "সাবহারমনিক",
    "resonance":            "রেজোন্যান্স",
    "formant frequency":    "ফরম্যান্ট কম্পাঙ্ক",
    "spectral centroid":    "স্পেকট্রাল সেন্ট্রয়েড",
    "spectral flux":        "স্পেকট্রাল ফ্লাক্স",
    "spectral rolloff":     "স্পেকট্রাল রোল-অফ",
    "spectral bandwidth":   "স্পেকট্রাল ব্যান্ডউইথ",

    # --- Additional Speech & Phonetics ---
    "coarticulation":       "কোআর্টিকুলেশন",
    "phonology":            "ধ্বনিবিজ্ঞান",
    "phonetics":            "ধ্বনিবিজ্ঞান (ধ্বনিতত্ত্ব)",
    "articulatory phonetics":"আর্টিকুলেটরি ফনেটিক্স",
    "acoustic phonetics":   "অ্যাকোস্টিক ফনেটিক্স",
    "prosodic features":    "প্রোসডিক বৈশিষ্ট্য",
    "speech rate":          "বাকের গতি",
    "speaking style":       "বক্তৃতার ধরন",
    "stress":               "জোর / স্ট্রেস",
    "tone":                 "স্বর",
    "pause":                "বিরতি",
    "disfluency":           "অপ্রবাহমানতা",
    "utterance":            "উচ্চারণিত বাক্যাংশ",
    "segment":              "সেগমেন্ট",
    "phone":                "ফোন (ধ্বনি একক)",
    "syllable boundary":    "সিলেবল সীমানা",
    "word boundary":        "শব্দ সীমানা",
    "tokenization":         "টোকেনাইজেশন",
    "grapheme-to-phoneme":  "গ্রাফিম-টু-ফোনিম রূপান্তর",
    "phonotactics":         "ফোনোট্যাকটিক্স",
    "language family":      "ভাষা পরিবার",
    "morphology":           "রূপতত্ত্ব",
    "syntax":               "বাক্যতত্ত্ব",
    "semantics":            "অর্থতত্ত্ব",
    "pragmatics":           "প্রয়োগতত্ত্ব",

    # --- Machine Learning Basics ---
    "machine learning":     "মেশিন লার্নিং",
    "supervised learning":  "সুপারভাইজড লার্নিং",
    "unsupervised learning":"আনসুপারভাইজড লার্নিং",
    "semi-supervised learning": "সেমি-সুপারভাইজড লার্নিং",
    "reinforcement learning":"রিইনফোর্সমেন্ট লার্নিং",
    "classification":       "শ্রেণীবিন্যাস",
    "regression":           "রিগ্রেশন",
    "clustering":           "ক্লাস্টারিং",
    "feature":              "ফিচার (বৈশিষ্ট্য)",
    "label":                "লেবেল",
    "training data":        "প্রশিক্ষণ ডেটা",
    "validation data":      "ভ্যালিডেশন ডেটা",
    "test data":            "টেস্ট ডেটা",
    "ground truth":         "গ্রাউন্ড ট্রুথ (বাস্তব মান)",
    "overfitting":          "ওভারফিটিং",
    "underfitting":         "আন্ডারফিটিং",
    "generalization":       "জেনারালাইজেশন",
    "feature engineering":  "ফিচার ইঞ্জিনিয়ারিং",
    "hyperparameter":       "হাইপারপ্যারামিটার",
    "parameter":            "প্যারামিটার",
    "training":             "প্রশিক্ষণ",
    "inference":            "ইনফারেন্স",
    "optimization":         "অপ্টিমাইজেশন",
    "objective function":   "উদ্দেশ্য ফাংশন",
    "loss function":        "লস ফাংশন",
    "cost function":        "কস্ট ফাংশন",
    "gradient descent":     "গ্রেডিয়েন্ট ডিসেন্ট",
    "stochastic gradient descent": "স্টোকাস্টিক গ্রেডিয়েন্ট ডিসেন্ট",
    "mini-batch gradient descent": "মিনি-ব্যাচ গ্রেডিয়েন্ট ডিসেন্ট",
    "learning rate":        "লার্নিং রেট",
    "momentum":             "মোমেন্টাম",
    "regularization":       "রেগুলারাইজেশন",
    "dropout":              "ড্রপআউট",
    "batch normalization":  "ব্যাচ নরমালাইজেশন",
    "early stopping":       "আর্লি স্টপিং",
    "epoch":                "ইপক",
    "batch size":           "ব্যাচ সাইজ",
    "iteration":            "ইটারেশন",
    "convergence":          "কনভার্জেন্স",
    "random initialization":"র‍্যান্ডম ইনিশিয়ালাইজেশন",
    "weight decay":         "ওয়েট ডিকেই",
    "gradient clipping":    "গ্রেডিয়েন্ট ক্লিপিং",
    "data augmentation":    "ডাটা অগমেন্টেশন",

    # --- Deep Learning & Architectures ---
    "deep neural network":  "ডিপ নিউরাল নেটওয়ার্ক",
    "convolutional neural network": "কনভলিউশনাল নিউরাল নেটওয়ার্ক",
    "fully connected layer":"ফুলি কানেক্টেড লেয়ার",
    "convolution layer":    "কনভলিউশন লেয়ার",
    "pooling layer":        "পুলিং লেয়ার",
    "max pooling":          "ম্যাক্স পুলিং",
    "average pooling":      "অ্যাভারেজ পুলিং",
    "activation function":  "অ্যাকটিভেশন ফাংশন",
    "relu":                 "রেলু ফাংশন",
    "sigmoid":              "সিগময়েড ফাংশন",
    "tanh":                 "ট্যানএইচ ফাংশন",
    "softmax":              "সফটম্যাক্স",
    "embedding":            "এম্বেডিং",
    "positional encoding":  "পজিশনাল এনকোডিং",
    "multi-head attention": "মাল্টি-হেড অ্যাটেনশন",
    "feed-forward network": "ফিড-ফরোয়ার্ড নেটওয়ার্ক",
    "residual connection":  "রেজিডুয়াল কানেকশন",
    "skip connection":      "স্কিপ কানেকশন",
    "layer normalization":  "লেয়ার নরমালাইজেশন",
    "gated recurrent unit": "গেটেড রিকারেন্ট ইউনিট (GRU)",
    "bidirectional rnn":    "বাইডাইরেকশনাল RNN",
    "sequence-to-sequence": "সিকোয়েন্স-টু-সিকোয়েন্স",
    "encoder-decoder":      "এনকোডার-ডিকোডার স্থাপত্য",
    "attention weight":     "অ্যাটেনশন ওজন",
    "context vector":       "কনটেক্সট ভেক্টর",
    "hidden state":         "হিডেন স্টেট",
    "cell state":           "সেল স্টেট",
    "beam width":           "বিম প্রস্থ",
    "greedy decoding":      "গ্রিডি ডিকোডিং",
    "sampling decoding":    "স্যাম্পলিং ডিকোডিং",

    # --- Evaluation Metrics ---
    "accuracy":             "নির্ভুলতা (অ্যাকুরেসি)",
    "precision":            "প্রিসিশন",
    "recall":               "রিকল",
    "f1 score":             "এফ১ স্কোর",
    "confusion matrix":     "কনফিউশন ম্যাট্রিক্স",
    "roc curve":            "আরওসি কার্ভ",
    "auc":                  "এরিয়া আন্ডার কার্ভ (AUC)",
    "perplexity":           "পারপ্লেক্সিটি",
    "bleu score":           "ব্লু স্কোর",
    "cer":                  "ক্যারেক্টার এরর রেট",
    "wer":                  "ওয়ার্ড এরর রেট",
    "false positive":       "ভুল ধনাত্মক (ফলস পজিটিভ)",
    "false negative":       "ভুল ঋণাত্মক (ফলস নেগেটিভ)",
    "true positive":        "সঠিক ধনাত্মক (ট্রু পজিটিভ)",
    "true negative":        "সঠিক ঋণাত্মক (ট্রু নেগেটিভ)",

    # --- Data & Corpora ---
    "dataset":              "ডেটাসেট",
    "corpus":               "করপাস",
    "annotation":           "অ্যানোটেশন",
    "labeling":             "লেবেলিং",
    "transcription":        "ট্রান্সক্রিপশন",
    "time alignment":       "টাইম অ্যালাইমেন্ট",
    "segment boundary":     "সেগমেন্ট সীমানা",
    "speaker label":        "স্পিকার লেবেল",
    "speaker identity":     "বক্তা পরিচয়",
    "speaker ID":           "স্পিকার আইডি",
    "sampling strategy":    "স্যাম্পলিং কৌশল",
    "stratified sampling":  "স্তরভিত্তিক স্যাম্পলিং",
    "data split":           "ডেটা বিভাজন",
    "train test split":     "ট্রেন-টেস্ট বিভাজন",
    "cross validation":     "ক্রস ভ্যালিডেশন",
    "k-fold validation":    "কে-ফোল্ড ভ্যালিডেশন",
    "data imbalance":       "ডেটা অমসৃণতা",
    "class imbalance":      "শ্রেণী অমসৃণতা",

    # --- Privacy & Security (More) ---
    "differential privacy": "ডিফারেনশিয়াল প্রাইভেসি",
    "federated learning":   "ফেডারেটেড লার্নিং",
    "encryption":           "এনক্রিপশন",
    "decryption":           "ডিক্রিপশন",
    "access control":       "অ্যাক্সেস কন্ট্রোল",
    "authentication":       "অথেন্টিকেশন",
    "authorization":        "অথরাইজেশন",
    "anonymization":        "অ্যানোনিমাইজেশন",
    "pseudonymization":     "ছদ্মনামকরণ",
    "data leakage":         "ডেটা লিকেজ",
    "security policy":      "সিকিউরিটি নীতি",
    "threat model":         "থ্রেট মডেল",
    "risk assessment":      "ঝুঁকি মূল্যায়ন",

    # --- Infrastructure, Systems & Deployment ---
    "central processing unit":  "সেন্ট্রাল প্রসেসিং ইউনিট (CPU)",
    "graphics processing unit": "গ্রাফিক্স প্রসেসিং ইউনিট (GPU)",
    "memory":               "মেমরি",
    "random access memory": "র‍্যান্ডম অ্যাক্সেস মেমরি (RAM)",
    "storage":              "স্টোরেজ",
    "solid state drive":    "সলিড স্টেট ড্রাইভ (SSD)",
    "hard disk drive":      "হার্ড ডিস্ক ড্রাইভ (HDD)",
    "operating system":     "অপারেটিং সিস্টেম",
    "process":              "প্রসেস",
    "thread":               "থ্রেড",
    "multi-threading":      "মাল্টি-থ্রেডিং",
    "scheduling":           "সিডিউলিং",
    "distributed system":   "ডিস্ট্রিবিউটেড সিস্টেম",
    "cluster":              "ক্লাস্টার",
    "node":                 "নোড",
    "container":            "কন্টেইনার",
    "containerization":     "কন্টেইনারাইজেশন",
    "virtual machine":      "ভার্চুয়াল মেশিন",
    "orchestration":        "অর্কেস্ট্রেশন",
    "kubernetes":           "কুবেরনেটিস",
    "docker":               "ডকার",
    "deployment":           "ডিপ্লয়মেন্ট",
    "continuous integration":"কনটিনিউয়াস ইন্টিগ্রেশন",
    "continuous delivery":  "কনটিনিউয়াস ডেলিভারি",
    "monitoring":           "মনিটরিং",
    "logging":              "লগিং",
    "profiling":            "প্রোফাইলিং",
    "scalability":          "স্কেলেবিলিটি",
    "horizontal scaling":   "হরাইজন্টাল স্কেলিং",
    "vertical scaling":     "ভার্টিক্যাল স্কেলিং",
    "load balancing":       "লোড ব্যাল্যান্সিং",
    "fault tolerance":      "ফল্ট টলারেন্স",
    "high availability":    "হাই অ্যাভেইলেবিলিটি",
    "service level agreement": "সার্ভিস লেভেল এগ্রিমেন্ট (SLA)",
    "throughput capacity":  "থ্রুপুট ক্ষমতা",
    "resource utilization": "রিসোর্স ব্যবহার",

    # --- Software Engineering & Tools ---
    "version control":      "ভার্সন কন্ট্রোল",
    "source code":          "সোর্স কোড",
    "repository":           "রিপোজিটরি",
    "branch":               "ব্রাঞ্চ",
    "commit":               "কমিট",
    "merge":                "মার্জ",
    "pull request":         "পুল রিকুয়েস্ট",
    "code review":          "কোড রিভিউ",
    "bug":                  "বাগ",
    "issue tracking":       "ইস্যু ট্র্যাকিং",
    "unit test":            "ইউনিট টেস্ট",
    "integration test":     "ইন্টিগ্রেশন টেস্ট",
    "regression test":      "রিগ্রেশন টেস্ট",
    "test coverage":        "টেস্ট কভারেজ",
    "debugging":            "ডিবাগিং",
    "configuration":        "কনফিগারেশন",
    "build system":         "বিল্ড সিস্টেম",
    "dependency":           "ডিপেনডেন্সি",
    "dependency management":"ডিপেনডেন্সি ম্যানেজমেন্ট",

    # --- Networking & Cloud ---
    "network latency":      "নেটওয়ার্ক ল্যাটেন্সি",
    "bandwidth utilization":"ব্যান্ডউইথ ব্যবহার",
    "packet loss":          "প্যাকেট লস",
    "protocol":             "প্রোটোকল",
    "application programming interface": "অ্যাপ্লিকেশন প্রোগ্রামিং ইন্টারফেস (API)",
    "rest api":             "রেস্ট এপিআই",
    "endpoint":             "এন্ডপয়েন্ট",
    "request":              "রিকুয়েস্ট",
    "response":             "রেসপন্স",
    "timeout":              "টাইমআউট",
    "retry":                "রিট্রাই",
    "rate limiting":        "রেট লিমিটিং",
    "cloud computing":      "ক্লাউড কম্পিউটিং",
    "infrastructure as a service": "ইনফ্রাস্ট্রাকচার অ্যাজ এ সার্ভিস (IaaS)",
    "platform as a service":      "প্ল্যাটফর্ম অ্যাজ এ সার্ভিস (PaaS)",
    "software as a service":      "সফটওয়্যার অ্যাজ এ সার্ভিস (SaaS)",
    "microservice":         "মাইক্রোসার্ভিস",
    "service discovery":    "সার্ভিস ডিসকভারি",
    "configuration service":"কনফিগারেশন সার্ভিস",

    # --- ASR / TTS Application Terms ---
    "automatic speech recognition": "অটোমেটিক স্পিচ রিকগনিশন",
    "speech recognition":   "বাক্‌ স্বীকৃতি",
    "keyword spotting":     "কীওয়ার্ড স্পটিং",
    "wake word":            "ওয়েক ওয়ার্ড",
    "voice assistant":      "ভয়েস অ্যাসিস্ট্যান্ট",
    "dialog system":        "ডায়ালগ সিস্টেম",
    "spoken language understanding": "স্পোকেন ল্যাঙ্গুয়েজ আন্ডারস্ট্যান্ডিং",
    "speech synthesis":     "বাক্‌ সংশ্লেষণ",
    "multilingual model":   "বহুভাষিক মডেল",
    "code switching":       "কোড সুইচিং",
    "accent":               "উচ্চারণভঙ্গি (অ্যাকসেন্ট)",
    "speaker adaptation":   "স্পিকার অ্যাডাপ্টেশন",
    "speaker normalization":"স্পিকার নরমালাইজেশন",
    "noise robustness":     "নয়েজ রোবাস্টনেস",
    "robustness":           "রোবাস্টনেস",
    "voice activity detection": "ভয়েস অ্যাক্টিভিটি ডিটেকশন",
    "endpointing":          "এন্ডপয়েন্টিং",
    "online decoding":      "অনলাইন ডিকোডিং",
    "offline decoding":     "অফলাইন ডিকোডিং",
    "streaming recognition":"স্ট্রিমিং রিকগনিশন",

    # --- Optimization & Math ---
    "vector":               "ভেক্টর",
    "matrix":               "ম্যাট্রিক্স",
    "tensor":               "টেনসর",
    "scalar":               "স্কেলার",
    "dot product":          "ডট প্রডাক্ট",
    "matrix multiplication":"ম্যাট্রিক্স গুণ",
    "eigenvalue":           "আইগেনভ্যালু",
    "eigenvector":          "আইগেনভেক্টর",
    "probability distribution": "প্রবাবিলিটি ডিস্ট্রিবিউশন",
    "gaussian distribution":"গাউসিয়ান ডিস্ট্রিবিউশন",
    "normal distribution":  "নরমাল ডিস্ট্রিবিউশন",
    "variance":             "ভ্যারিয়েন্স",
    "standard deviation":   "স্ট্যান্ডার্ড ডেভিয়েশন",
    "covariance":           "কোভ্যারিয়েন্স",
    "likelihood":           "লাইকলিহুড",
    "maximum likelihood estimation": "ম্যাক্সিমাম লাইকলিহুড এস্টিমেশন",
    "bayesian inference":   "বেয়েসিয়ান ইনফারেন্স",
    "prior":                "প্রায়র",
    "posterior":            "পোস্টেরিয়র",
    "gradient":             "গ্রেডিয়েন্ট",
    "hessian":              "হেসিয়ান ম্যাট্রিক্স",
    "convex function":      "কনভেক্স ফাংশন",
    "non-convex":           "নন-কনভেক্স",
    "local minimum":        "লোকাল মিনিমাম",
    "global minimum":       "গ্লোবাল মিনিমাম",

    # --- Experimentation & MLOps ---
    "experiment tracking":  "এক্সপেরিমেন্ট ট্র্যাকিং",
    "baseline model":       "বেসলাইন মডেল",
    "ablation study":       "অব্লেশন স্টাডি",
    "hyperparameter search":"হাইপারপ্যারামিটার সার্চ",
    "grid search":          "গ্রিড সার্চ",
    "random search":        "র‍্যান্ডম সার্চ",
    "bayesian optimization":"বেয়েসিয়ান অপ্টিমাইজেশন",
    "model serving":        "মডেল সার্ভিং",
    "model versioning":     "মডেল ভার্সনিং",
    "shadow deployment":    "শ্যাডো ডিপ্লয়মেন্ট",
    "canary release":       "ক্যানারি রিলিজ",
    "rollout":              "রোলআউট",
    "rollback":             "রোলব্যাক",
    "online evaluation":    "অনলাইন ইভালুয়েশন",
    "offline evaluation":   "অফলাইন ইভালুয়েশন",

    # --- Error Analysis & Diagnostics ---
    "error analysis":       "এরর অ্যানালাইসিস",
    "confusable word":      "সহজে গুলিয়ে ফেলা যায় এমন শব্দ",
    "pronunciation variant":"উচ্চারণের ভ্যারিয়েন্ট",
    "acoustic confusion":   "অ্যাকোস্টিক বিভ্রান্তি",
    "language confusion":   "ভাষাগত বিভ্রান্তি",
    "out-of-vocabulary":    "অভিধানবহির্ভূত (OOV)",
    "calibration":          "ক্যালিব্রেশন",
    "confidence score":     "কনফিডেন্স স্কোর",
    "threshold":            "থ্রেশহোল্ড",
    "false alarm":          "ভুল অ্যালার্ম",
    "miss rate":            "মিস রেট",

    # --- Miscellaneous Useful Terms ---
    "real time":            "রিয়েল-টাইম",
    "offline":              "অফলাইন",
    "latency constraint":   "ল্যাটেন্সি সীমাবদ্ধতা",
    "memory footprint":     "মেমরি ফুটপ্রিন্ট",
    "compute budget":       "কম্পিউট বাজেট",
    "energy efficiency":    "শক্তি দক্ষতা",
    "mobile deployment":    "মোবাইল ডিপ্লয়মেন্ট",
    "edge device":          "এজ ডিভাইস",
    "embedded system":      "এম্বেডেড সিস্টেম",
    "benchmark":            "বেঞ্চমার্ক",
    "production system":    "প্রোডাকশন সিস্টেম",
    "prototype":            "প্রোটোটাইপ",
    "research model":       "গবেষণা মডেল",
    # --- General-purpose everyday vocabulary: People & Family ---
    "person":               "মানুষ",
    "man":                  "পুরুষ",
    "woman":                "মহিলা",
    "child":                "শিশু",
    "boy":                  "ছেলে",
    "girl":                 "মেয়ে",
    "friend":               "বন্ধু",
    "family":               "পরিবার",
    "father":               "বাবা",
    "mother":               "মা",
    "son":                  "পুত্র",
    "daughter":             "কন্যা",
    "brother":              "ভাই",
    "sister":               "বোন",
    "husband":              "স্বামী",
    "wife":                 "স্ত্রী",
    "colleague":            "সহকর্মী",
    "neighbor":             "প্রতিবেশী",
    "teacher":              "শিক্ষক",
    "student":              "ছাত্র / ছাত্রী",

    # --- Daily activities & common verbs ---
    "to go":                "যাওয়া",
    "to come":              "আসা",
    "to eat":               "খাওয়া",
    "to drink":             "পান করা",
    "to sleep":             "ঘুমানো",
    "to wake up":           "জাগা",
    "to work":              "কাজ করা",
    "to study":             "পড়াশোনা করা",
    "to read":              "পড়া",
    "to write":             "লেখা",
    "to speak":             "কথা বলা",
    "to listen":            "শোনা",
    "to see":               "দেখা",
    "to look":              "তাকানো",
    "to think":             "ভাবা",
    "to know":              "জানা",
    "to understand":        "বোঝা",
    "to like":              "পছন্দ করা",
    "to love":              "ভালবাসা",
    "to need":              "প্রয়োজন হওয়া",
    "to want":              "চাওয়া",
    "to buy":               "কেনা",
    "to sell":              "বিক্রি করা",
    "to call":              "ফোন করা / ডাকা",
    "to wait":              "অপেক্ষা করা",

    # --- Time & calendar ---
    "today":                "আজ",
    "yesterday":            "গতকাল",
    "tomorrow":             "আগামীকাল",
    "day":                  "দিন",
    "night":                "রাত",
    "morning":              "সকাল",
    "afternoon":            "বিকেল",
    "evening":              "সন্ধ্যা",
    "week":                 "সপ্তাহ",
    "month":                "মাস",
    "year":                 "বছর",
    "hour":                 "ঘণ্টা",
    "minute":               "মিনিট",
    "second":               "সেকেন্ড",
    "holiday":              "ছুটির দিন",
    "festival":             "উৎসব",
    "birthday":             "জন্মদিন",

    # --- Numbers (0–20, tens) ---
    "zero":                 "শূন্য",
    "one":                  "এক",
    "two":                  "দুই",
    "three":                "তিন",
    "four":                 "চার",
    "five":                 "পাঁচ",
    "six":                  "ছয়",
    "seven":                "সাত",
    "eight":                "আট",
    "nine":                 "নয়",
    "ten":                  "দশ",
    "eleven":               "এগারো",
    "twelve":               "বারো",
    "thirteen":             "তেরো",
    "fourteen":             "চৌদ্দ",
    "fifteen":              "পনেরো",
    "sixteen":              "ষোলো",
    "seventeen":            "সতেরো",
    "eighteen":             "আঠারো",
    "nineteen":             "উনিশ",
    "twenty":               "বিশ",
    "thirty":               "ত্রিশ",
    "forty":                "চল্লিশ",
    "fifty":                "পঞ্চাশ",
    "sixty":                "ষাট",
    "seventy":              "সত্তর",
    "eighty":               "আশি",
    "ninety":               "নব্বই",
    "hundred":              "একশো",

    # --- Common adjectives ---
    "big":                  "বড়",
    "small":                "ছোট",
    "long":                 "লম্বা",
    "short":                "খাটো / ছোট",
    "new":                  "নতুন",
    "old":                  "পুরোনো",
    "good":                 "ভাল",
    "bad":                  "খারাপ",
    "easy":                 "সহজ",
    "difficult":            "কঠিন",
    "fast":                 "দ্রুত",
    "slow":                 "ধীরে",
    "hot":                  "গরম",
    "cold":                 "ঠান্ডা",
    "near":                 "কাছাকাছি",
    "far":                  "দূর",
    "right":                "সঠিক",
    "wrong":                "ভুল",
    "same":                 "একই",
    "different":            "ভিন্ন",

    # --- Basic objects & places ---
    "home":                 "বাড়ি",
    "house":                "ঘর",
    "room":                 "ঘর / কক্ষ",
    "office":               "অফিস",
    "school":               "স্কুল",
    "university":           "বিশ্ববিদ্যালয়",
    "road":                 "রাস্তা",
    "street":               "রাস্তা",
    "city":                 "শহর",
    "village":              "গ্রাম",
    "market":               "বাজার",
    "shop":                 "দোকান",
    "restaurant":           "রেস্তোরাঁ",
    "hospital":             "হাসপাতাল",
    "station":              "স্টেশন",
    "airport":              "বিমানবন্দর",
    "park":                 "পার্ক",
    "bank":                 "ব্যাংক",

    # --- Food & drink ---
    "water":                "পানি",
    "tea":                  "চা",
    "coffee":               "কফি",
    "milk":                 "দুধ",
    "rice":                 "ভাত",
    "bread":                "রুটি / পাউরুটি",
    "egg":                  "ডিম",
    "fish":                 "মাছ",
    "meat":                 "মাংস",
    "vegetable":            "সবজি",
    "fruit":                "ফল",
    "salt":                 "লবণ",
    "sugar":                "চিনি",
    "spice":                "মসলা",
    "breakfast":            "নাশতা",
    "lunch":                "দুপুরের খাবার",
    "dinner":               "রাতের খাবার",

    # --- Weather & nature ---
    "weather":              "আবহাওয়া",
    "sun":                  "সূর্য",
    "rain":                 "বৃষ্টি",
    "cloud":                "মেঘ",
    "wind":                 "হাওয়া",
    "storm":                "ঝড়",
    "hot weather":          "গরম আবহাওয়া",
    "cold weather":         "শীতল আবহাওয়া",
    "summer":               "গ্রীষ্ম",
    "winter":               "শীত",
    "rainy season":         "বর্ষা",
    "spring":               "বসন্ত",
    "autumn":               "শরৎ",
    "earth":                "পৃথিবী",
    "sky":                  "আকাশ",
    "river":                "নদী",
    "sea":                  "সমুদ্র",
    "tree":                 "গাছ",
    "flower":               "ফুল",

    # --- Basic technology & communication ---
    "phone":                "ফোন",
    "mobile phone":         "মোবাইল ফোন",
    "computer":             "কম্পিউটার",
    "laptop":               "ল্যাপটপ",
    "internet":             "ইন্টারনেট",
    "message":              "বার্তা",
    "email":                "ইমেইল",
    "password":             "পাসওয়ার্ড",
    "meeting":              "মিটিং / সভা",
    "video call":           "ভিডিও কল",
    "chat":                 "চ্যাট",
    "file":                 "ফাইল",
    "folder":               "ফোল্ডার",

    # --- Common expressions & politeness ---
    "hello":                "হ্যালো / নমস্কার",
    "good morning":         "সুপ্রভাত",
    "good evening":         "শুভ সন্ধ্যা",
    "good night":           "শুভ রাত্রি",
    "how are you":          "আপনি কেমন আছেন",
    "i am fine":            "আমি ভাল আছি",
    "thank you":            "ধন্যবাদ",
    "you are welcome":      "স্বাগতম",
    "please":               "অনুগ্রহ করে",
    "sorry":                "দুঃখিত",
    "excuse me":            "মাফ করবেন",
    "yes":                  "হ্যাঁ",
    "no":                   "না",
    "maybe":                "হয়তো",
    "okay":                 "ঠিক আছে",
    "see you later":        "আবার দেখা হবে",
    "good luck":            "শুভ কামনা",
    "congratulations":      "অভিনন্দন",
    "best wishes":          "শুভেচ্ছা",
    # --- Modern Foundation Models & Training ---
    "foundation model":         "ফাউন্ডেশন মডেল",
    "self-supervised learning":  "সেলফ-সুপারভাইজড লার্নিং",
    "weak supervision":         "উইক সুপারভিশন",
    "zero-shot cloning":        "জিরো-শট ক্লোনিং",
    "few-shot learning":        "ফিউ-শট লার্নিং",
    "pre-training":             "প্রি-ট্রেনিং",
    "fine-tuning":              "ফাইন-টিউনিং",
    "prompt engineering":       "প্রম্পট ইঞ্জিনিয়ারিং",
    
    # --- Advanced Architectures ---
    "latent diffusion":         "ল্যাটেন্ট ডিফিউশন",
    "multimodal perception":    "মাল্টিমোডাল পারসেপশন",
    "cross-lingual transfer":   "ক্রস-লিঙ্গুয়াল ট্রান্সফার",
    "neural vocoder":           "নিউরাল ভোকোডার",
    "transformer block":        "ট্রান্সফর্মার ব্লক",
    "conformer":                "কনফর্মার",
    "state space model":        "স্টেট স্পেস মডেল (SSM)",
    "mamba architecture":       "মাম্বা আর্কিটেকচার",
    "vector embedding":         "ভেক্টর এমবেডিং",
    "bottleneck layer":         "বটলনেক লেয়ার",

    # --- Speech Security & Privacy ---
    "privacy preserving":       "গোপনীয়তা রক্ষাকারী",
    "machine unlearning":       "মেশিন আনলার্নিং",
    "differential privacy":     "ডিফারেনশিয়াল প্রাইভেসি",
    "voice biometrics":         "ভয়েস বায়োমেট্রিক্স",
    "deepfake detection":       "ডিপফেক ডিটেকশন",
    "anti-spoofing":            "অ্যান্টি-স্পুফিং",
    "adversarial attack":       "অ্যাডভারসারিয়াল অ্যাটাক",
    "membership inference":     "মেম্বারশিপ ইনফারেন্স",

    # --- Real-time & Deployment ---
    "low-latency":              "লো-ল্যাটেন্সি (স্বল্প বিলম্ব)",
    "throughput":               "থ্রুপুট",
    "inference engine":         "ইনফারেন্স ইঞ্জিন",
    "quantized model":          "কোয়ান্টাইজড মডেল",
    "edge computing":           "এজ কম্পিউটিং",
    "streaming asr":            "স্ট্রিমিং এএসআর",
    "on-device processing":     "অন-ডিভাইস প্রসেসিং",

    # --- Conversational AI ---
    "agentic ai":               "এজেন্টিক এআই",
    "dialogue management":      "ডায়ালগ ম্যানেজমেন্ট",
    "natural language understanding": "ন্যাচারাল ল্যাঙ্গুয়েজ আন্ডারস্ট্যান্ডিং (NLU)",
    "intent recognition":       "ইনটেন্ট রিকগনিশন (অভিপ্রায় শনাক্তকরণ)",
    "hallucination":            "হ্যালুসিনেশন (বিভ্রান্তি)",
    "retrieval augmented generation": "রিট্রিভাল অগমেন্টেড জেনারেশন (RAG)",
    "knowledge graph":          "নলেজ গ্রাফ",
    "semantic search":          "সিম্যান্টিক সার্চ",

    # --- General Technical/System (HPC) ---
    "shared library":           "শেয়ারড লাইব্রেরি",
    "binary interface":         "বাইনারি ইন্টারফেস (ABI)",
    "environment variable":     "এনভায়রনমেন্ট ভেরিয়েবল",
    "dependency resolution":    "ডিপেন্ডেন্সি রেজোলিউশন",
    "containerization":         "কন্টেইনারাইজেশন",
    
    "व्यक्ति":              "মানুষ",
    "आदमी":                "পুরুষ",
    "औरत":                "মহিলা",
    "बच्चा":               "শিশু",
    "लड़का":               "ছেলে",
    "लड़की":               "মেয়ে",
    "दोस्त":               "বন্ধু",
    "परिवार":              "পরিবার",
    "पिता":               "বাবা",
    "माँ":                "মা",
    "बेटा":               "পুত্র",
    "बेटी":               "কন্যা",
    "भाई":                "ভাই",
    "बहन":                "বোন",
    "पति":                "স্বামী",
    "पत्नी":               "স্ত্রী",
    "सहकर्मी":            "সহকর্মী",
    "पड़ोसी":             "প্রতিবেশী",
    "शिक्षक":             "শিক্ষক",
    "विद्यार्थी":          "ছাত্র / ছাত্রী",

    # --- Daily activities & common verbs ---
    "जाना":               "যাওয়া",
    "आना":               "আসা",
    "खाना":              "খাওয়া",
    "पीना":              "পান করা",
    "सोना":              "ঘুমানো",
    "जागना":             "জাগা",
    "काम करना":          "কাজ করা",
    "पढ़ाई करना":        "পড়াশোনা করা",
    "पढ़ना":             "পড়া",
    "लिखना":             "লেখা",
    "बात करना":          "কথা বলা",
    "सुनना":             "শোনা",
    "देखना":             "দেখা",
    "सोचना":             "ভাবা",
    "जानना":             "জানা",
    "समझना":            "বোঝা",
    "पसंद करना":         "পছন্দ করা",
    "प्यार करना":        "ভালবাসা",
    "ज़रूरत होना":       "প্রয়োজন হওয়া",
    "चाहना":             "চাওয়া",
    "खरीदना":            "কেনা",
    "बेचना":             "বিক্রি করা",
    "फोन करना":          "ফোন করা",
    "इंतज़ार करना":      "অপেক্ষা করা",

    # --- Time & calendar ---
    "आज":                "আজ",
    "बीता कल":           "গতকাল",
    "आने वाला कल":       "আগামীকাল",
    "दिन":               "দিন",
    "रात":               "রাত",
    "सुबह":              "সকাল",
    "दोपहर":            "বিকেল",
    "शाम":               "সন্ধ্যা",
    "हफ़्ता":            "সপ্তাহ",
    "महीना":             "মাস",
    "साल":               "বছর",
    "घंटा":              "ঘণ্টা",
    "मिनट":              "মিনিট",
    "सेकंड":            "সেকেন্ড",
    "छुट्टी का दिन":     "ছুটির দিন",
    "त्योहार":           "উৎসব",
    "जन्मदिन":          "জন্মদিন",

    # --- Numbers ---
    "शून्य":             "শূন্য",
    "एक":                "এক",
    "दो":                "দুই",
    "तीन":               "তিন",
    "चार":               "চার",
    "पाँच":              "পাঁচ",
    "छह":               "ছয়",
    "सात":               "সাত",
    "आठ":               "আট",
    "नौ":                "নয়",
    "दस":               "দশ",
    "ग्यारह":            "এগারো",
    "बारह":              "বারো",
    "तेरह":              "তেরো",
    "चौदह":             "চৌদ্দ",
    "पंद्रह":            "পনেরো",
    "सोलह":             "ষোলো",
    "सत्रह":            "সতেরো",
    "अठारह":           "আঠারো",
    "उन्नीस":           "উনিশ",
    "बीस":              "বিশ",
    "तीस":              "ত্রিশ",
    "चालीस":           "চল্লিশ",
    "पचास":             "পঞ্চাশ",
    "साठ":              "ষাট",
    "सत्तर":            "সত্তর",
    "अस्सी":            "আশি",
    "नब्बे":            "নব্বই",
    "सौ":               "একশো",

    # --- Common adjectives ---
    "बड़ा":             "বড়",
    "छोटा":             "ছোট",
    "लंबा":             "লম্বা",
    "नया":              "নতুন",
    "पुराना":           "পুরোনো",
    "अच्छा":            "ভাল",
    "बुरा":             "খারাপ",
    "आसान":            "সহজ",
    "कठिन":            "কঠিন",
    "तेज़":             "দ্রুত",
    "धीमा":             "ধীরে",
    "गर्म":             "গরম",
    "ठंडा":             "ঠান্ডা",
    "पास":              "কাছাকাছি",
    "दूर":              "দূর",
    "सही":              "সঠিক",
    "गलत":             "ভুল",
    "एक जैसा":          "একই",
    "अलग":             "ভিন্ন",

    # --- Basic objects & places ---
    "घर":               "বাড়ি",
    "मकान":             "ঘর",
    "कमरा":             "ঘর / কক্ষ",
    "दफ़्तर":           "অফিস",
    "स्कूल":            "স্কুল",
    "विश्वविद्यालय":     "বিশ্ববিদ্যালয়",
    "सड़क":             "রাস্তা",
    "गली":              "রাস্তা",
    "शहर":              "শহর",
    "गाँव":             "গ্রাম",
    "बाज़ार":           "বাজার",
    "दुकान":            "দোকান",
    "रेस्टोरेंट":       "রেস্তোরাঁ",
    "अस्पताल":          "হাসপাতাল",
    "स्टेशन":           "স্টেশন",
    "हवाई अड्डा":       "বিমানবন্দর",
    "पार्क":             "পার্ক",
    "बैंक":             "ব্যাংক",

    # --- Food & drink ---
    "पानी":             "পানি",
    "चाय":              "চা",
    "कॉफ़ी":            "কফি",
    "दूध":              "দুধ",
    "चावल":             "ভাত",
    "रोटी":             "রুটি",
    "ब्रेड":            "পাউরুটি",
    "अंडा":             "ডিম",
    "मछली":             "মাছ",
    "मांस":             "মাংস",
    "सब्ज़ी":           "সবজি",
    "फल":               "ফল",
    "नमक":             "লবণ",
    "चीनी":            "চিনি",
    "मसाला":           "মসলা",
    "नाश्ता":          "নাশতা",
    "दोपहर का खाना":   "দুপুরের খাবার",
    "रात का खाना":      "রাতের খাবার",

    # --- Weather & nature ---
    "मौसम":            "আবহাওয়া",
    "सूरज":             "সূর্য",
    "बारिश":            "বৃষ্টি",
    "बादल":             "মেঘ",
    "हवा":              "হাওয়া",
    "तूफ़ान":          "ঝড়",
    "गरम मौसम":        "গরম আবহাওয়া",
    "ठंडा मौसम":       "শীতল আবহাওয়া",
    "गर्मी":            "গ্রীষ্ম",
    "सर्दी":            "শীত",
    "बरसात":           "বর্ষা",
    "बसंत":            "বসন্ত",
    "पतझड़":           "শরৎ",
    "धरती":            "পৃথিবী",
    "आसमान":           "আকাশ",
    "नदी":              "নদী",
    "समुद्र":           "সমুদ্র",
    "पेड़":             "গাছ",
    "फूल":             "ফুল",

    # --- Basic technology & communication ---
    "फ़ोन":             "ফোন",
    "मोबाइल फ़ोन":      "মোবাইল ফোন",
    "कम्प्यूटर":         "কম্পিউটার",
    "लैपटॉप":           "ল্যাপটপ",
    "इंटरनेट":         "ইন্টারনেট",
    "संदेश":            "বার্তা",
    "ईमेल":            "ইমেইল",
    "पासवर्ड":         "পাসওয়ার্ড",
    "मीटिंग":          "মিটিং",
    "बैठक":            "সভা",
    "वीडियो कॉल":      "ভিডিও কল",
    "चैट":             "চ্যাট",
    "फ़ाइल":            "ফাইল",
    "फ़ोल्डर":          "ফোল্ডার",

    # --- Common expressions & politeness ---
    "नमस्ते":           "হ্যালো / নমস্কার",
    "सुप्रभात":         "সুপ্রভাত",
    "शुभ संध्या":       "শুভ সন্ধ্যা",
    "शुभ रात्रि":       "শুভ রাত্রি",
    "आप कैसे हैं":      "আপনি কেমন আছেন",
    "मैं ठीक हूँ":      "আমি ভাল আছি",
    "धन्यवाद":         "ধন্যবাদ",
    "स्वागत है":        "স্বাগতম",
    "कोई बात नहीं":     "কিছু না / সমস্যা নেই",
    "कृपया":           "অনুগ্রহ করে",
    "माफ़ कीजिए":      "দুঃখিত / মাফ করবেন",
    "हाँ":              "হ্যাঁ",
    "नहीं":             "না",
    "शायद":            "হয়তো",
    "ठीक है":          "ঠিক আছে",
    "फिर मिलेंगे":      "আবার দেখা হবে",
    "शुभकामनाएँ":       "শুভ কামনা / শুভেচ্ছা",
    "बधाई हो":         "অভিনন্দন"



}